### ISSUE TITLE
Make it easier to click Refresh after adding fields on Display tab

### ISSUE THREAD

**Issue by TooMuchBlue** [CSI-Inc/imis-experience-plus#12]
When working with a query with many objects and many fields, you might have to scroll way down the page to find the new field you want.  When you're done, you have to scroll all the way back to click the Refresh button.

I would like to see a button which is always visible on long pages which either scrolls to the top of the page to make the Refresh button visible, or which does the same thing as the Refresh button.  The pinned bar for SQL Expression might be a good place to show the new button.

**Comment by TooMuchBlue** [comment]
Duplicate of #8

**Comment by csijake** [comment]
FYI @TooMuchBlue this was added to the next upcoming release (due out in a week or two).
