### ISSUE TITLE
Saving an IQA has overlays

### ISSUE THREAD

**Issue by causeisash** [CSI-Inc/imis-experience-plus#15]
Open an IQA - View default columns, then click save as - the Selected and Available overlays on the popup window

![image](https://github.com/CSI-Inc/imis-experience-plus/assets/120602963/a310f83e-7ead-46e9-90a2-034a157889ad)

**Comment by pennltrex** [comment]
It looks like part of this has been fixed, but the SQL Expression area still overlays the save dialog.

![image](https://github.com/CSI-Inc/imis-experience-plus/assets/8291512/bd3fbd7f-93f9-4951-80a4-27f6ff58a422)

**Comment by jruss23** [comment]
This has been fix as of 1.3.4 which is live in Chrome but pending in Edge (eta 1 week).
