### ISSUE TITLE
2017 - Filter Width Too Small

### ISSUE THREAD

**Issue by csiMatthew** [CSI-Inc/imis-experience-plus#23]
## Description

The filters for IQA queries in 2017 are too narrow: 

https://drive.google.com/file/d/1ooR0JkEh25TjI2oqyfLoqz_MLgphg3Bu/view?usp=drivesdk

## Steps to Reproduce
Load the IQA editor part of iMIS Experience Plus and notice the smaller width items.

**Comment by csijake** [comment]
Confirmed - will be addressed in the next release (ETA 1-2 weeks).

**Comment by jruss23** [comment]
This has been fix as of 1.3.4 which is live in Chrome but pending in Edge (eta 1 week).
