### ISSUE TITLE
The date is collapse/hidden on IQA filter

### ISSUE THREAD

**Issue by npav1002** [CSI-Inc/imis-experience-plus#24]
## Description

When adding a filter date on filter of an IQA, the with of the date box is quite small and we can't see the selected date value. It seems the CSS  width: calc (100% - 193 px) was causing this issue. We tried to untick this CSS in from Chrome development tool and it showed the date value.
 

## Environment
This issue happens on the Chrome and Edge browsers.

![image](https://github.com/CSI-Inc/imis-experience-plus/assets/95191923/b2b68130-8af2-471a-bb70-ce3c17e0a662)

**Comment by jruss23** [comment]
This has been fix as of 1.3.4 which is live in Chrome but pending in Edge (eta 1 week).
