### ISSUE TITLE
Date between filter size issue

### ISSUE THREAD

**Issue by Kaizillian** [CSI-Inc/imis-experience-plus#27]
## Description

Define filter of date range display issue. preset value can not be seen.

![image](https://github.com/CSI-Inc/imis-experience-plus/assets/150318394/abde280f-69b2-4519-b5b2-293eb11d68a4)
![image](https://github.com/CSI-Inc/imis-experience-plus/assets/150318394/2433acc3-5853-4c80-8356-ceb01f428717)

## Steps to Reproduce

Open IQA, adding filter for date entity. choose the 'between' of the comparison. the pre-selected value can not be seen.

## Environment

it's been found on the Chrome (Version 119.0.6045.106 )

**Comment by jruss23** [comment]
This has been fix as of 1.3.4 which is live in Chrome but pending in Edge (eta 1 week).
