### ISSUE TITLE
SQL Edit Button Not Appearing Consistently

### ISSUE THREAD

**Issue by mkgAXO** [CSI-Inc/imis-experience-plus#5]
Hi CSI friends - Yay for this tool! 

Hello from Marsha at Alpha Chi Omega. 

I downloaded the extension last week - probably before your bug fix has gone live, so if your fix will address my issues, just tell me to be patient.

I created an IQA with a bunch of SQL statements ($/ACOFND/Mid-Level/Mid-Level Audience Individual Metrics) - y'all have access to our iMIS instance, so feel free to take a look.

When I created it on Sunday 10/23, I could see the orange Edit button beside the SQL in the Display tab for many of the SQL statements. However, it didn't show up on any of the SQL statements that started with FORMAT. I'm not sure if that was the "why" but that was the consistent issue with all of the statements that didn't show an Edit button.

Today, I don't see the Edit button for any of them. I tried removing the Google extension and then re-adding it but that doesn't seem to help. Just wanted to submit this as an issue so you could take a look at what might be causing it.

Thanks for creating is!

**Comment by TooMuchBlue** [comment]
Same issue.  I get the edit button for this formula:
`convert(datetime, vBoNetContactBasic.MemberTypeChangeDate)`
but not for this formula:
`convert(varchar(33), vBoNetContactBasic.MemberTypeChangeDate, 126)`

It doesn't matter which order they appear in the list.

**Comment by TooMuchBlue** [comment]
I did some digging on this.  It appears that the problem only occurs when a SQL Expression results in a string/character result.  The extension detects calculated fields in part by noticing that the Function column dropdown has only one available choice.  String SQL expressions still have more choices.

One idea on how this might be fixed is to add an empty SQL comment /**/ to the end of any calculation while saving.  Then if the script sees this text appearing inside the Property column, it could recognize this as a calculation.

**Comment by csijake** [comment]
Hi all, we have addressed this in the next version (due out within the next week or two). Unfortunately there isn't a way to know for sure which table rows are custom SQL versus not, however I added some code to attempt to "guess" which looks for certain text items that can only appear in custom SQL (things like `(` ... `)` or `CASE WHEN`). This should hopefully address most, if not all, edge cases.

**Comment by csijake** [comment]
Closing - should be fixed or at least as good as we can get it without ASI adding something into iMIS itself. 🙂

**Comment by TooMuchBlue** [comment]
Thanks for the fix!  I agree that '(' with ')' is a good test.  It also gives us an easy and relatively safe way to force it to be recognized as SQL when it doesn't already match a pattern.  If think of anything else useful, I'll submit a PR to add more patterns.
